### ISSUE TITLE
expose nvim-binding as a crate

### ISSUE THREAD

**Issue by kkharji** [noib3/nvim-compleet#15]
Hello @noib3, amazing work so far, I'm facing similar issues that I found nvim-binding supper helpful and I was considering creating one similar. It would be great if you can extract it to it's own repo and release it on crate.io. I intend to use so maybe I could contribute as I go

Thanks.

**Comment by noib3** [comment]
Yes, I already had in mind to move `nvim-bindings` to its own crate after refactoring it. It could provide a nice way for plugin authors to write their plugins in Rust. There's also the [overkill_nvim](https://github.com/turboladen/overkill_nvim) project which provides FFI bindings to the `vim.api` functions which are written in C.

**Comment by noib3** [comment]
@tami5 This is now [being worked on](https://github.com/noib3/nvim-oxi). Any help is more than welcome.

**Comment by noib3** [comment]
https://github.com/noib3/nvim-oxi
