### ISSUE TITLE
Take some appreciation ;)

### ISSUE THREAD

**Issue by RaafatTurki** [noib3/nvim-compleet#17]
You're a machine!
I've been visiting this repo for the past few months every once in a while and each time I do I see you committing something a few days ago.

Seeing a project of this size and `nvim-oxi` being held up by one person is a feat to admire.
Take your time and have fun developing this ;)

**Comment by noib3** [comment]
Hey thanks a lot! I'm rewriting this from scratch using `nvim-oxi` so it'll still be a while before it's ready for a `0.1` release. I'll make sure to have fun though ;)
