### ISSUE TITLE
Not working on ubuntu 20.04 

### ISSUE THREAD

**Issue by zjp-CN** [noib3/nvim-compleet#2]
Thank you for the pure Rust plugin for nvim! But this plugin doesn't run on my computer. 
I use nvim0.6 and update nvim to 0.7 for nvim-compleet.
Version: NVIM v0.7.0-dev+1341-g79dcd045d (officially build binary on github release today)

https://user-images.githubusercontent.com/25300418/160394054-177e684c-286f-4604-8fb8-00d10307f65b.mp4

[Here](https://github.com/zjp-CN/nvim-0.7/tree/nvim-compleet) is the minimum configuration just for nvim-compleet.
You can see the ` CompleetStart` and `CompleetStop` commands exists, and nothing occurs when keys are stroked

**Comment by noib3** [comment]
The plugin is running fine, it's just that no useful sources have been implemented yet. The only source currently available is `lipsum`, which by looking at your config I believe you have already enabled.

Try typing the `s` character. A bunch of senseless words should come up.

**Comment by zjp-CN** [comment]
> Try typing the `s` character. A bunch of senseless words should come up.

Well, nothing comes up.

**Comment by noib3** [comment]
What's the output of `:au Compleet`?

**Comment by zjp-CN** [comment]
```VIM
:au Compleet
--- Autocommands ---
Compleet  BufEnter
    *         <Lua function 5>
```

**Comment by noib3** [comment]
Mh, seems like no buffer is attached. What's the output of that same command after a `:CompleetStart`? Also, what does `:mes` say?

**Comment by zjp-CN** [comment]
> What's the output of that same command after a `:CompleetStart`?

[nvim-compleet] Started completion in buffer 5

> what does `:mes` say?

[nvim-compleet] Started completion in buffer 5
[nvim-compleet] Completion is already off in this buffer
[nvim-compleet] Started completion in buffer 5
[nvim-compleet] Completion is already off in this buffer
[nvim-compleet] Started completion in buffer 5

**Comment by zjp-CN** [comment]
if I start a new nvim, and type  `:CompleetStart`, all the `:mes` is
`[nvim-compleet] Started completion in buffer 1`.

**Comment by zjp-CN** [comment]
Then type `s` character in insert mode, still get nothing more.

**Comment by noib3** [comment]
I cannot reproduce.

Can you try these steps:
- `nvim -u NONE`
- `:lua require('compleet').setup({sources={lipsum={enable=true}}})`
- `:CompleetStart`

If that still doesn't work, try recompiling the plugin with `RUSTFLAGS='--cfg debug' cargo build --release && make install` inside the install directory. `nvim-compleet` should print the current settings after `require('compleet').setup({..})`.

**Comment by zjp-CN** [comment]
> Can you try these steps:

These three steps works!

**Comment by zjp-CN** [comment]
Yes. And I resolved it. Thank you.
