### ISSUE TITLE
(Feature request): coc nvim support

### ISSUE THREAD

**Issue by andrey-mouk** [noib3/nvim-compleet#6]
coc nvim support (?)

**Comment by noib3** [comment]
What are you asking exactly? coc.nvim is basically an LSP client, is this about adding an LSP source?

**Comment by andrey-mouk** [comment]
@noib3  yeah, maybe, I'm asking because coc uses native autocomplete, and it's kind of ugly, that's it

**Comment by noib3** [comment]
`nvim-compleet` uses floating windows which, unlike the native popup menu, are fully themeable. And yes, the LSP source is being worked on.
